; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28314.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\miuta\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
